PACKAGE_NAME=xt_setset
pushd `dirname $BASH_SOURCE`
PACKAGE_VERSION=`./version.sh`
popd
BUILT_MODULE_NAME[0]=xt_setset
DEST_MODULE_LOCATION[0]=/kernel/extra
STRIP[0]=no
BUILT_MODULE_NAME[1]=xt_banset
DEST_MODULE_LOCATION[1]=/kernel/extra
STRIP[1]=no
BUILT_MODULE_NAME[2]=x4b_banset_hook
DEST_MODULE_LOCATION[2]=/kernel/extra
STRIP[2]=no
MAKE[0]="make xt_setset.ko KCFLAGS=-O3"
PRE_BUILD="./configure --from-dkms-conf=$kernel_source_dir"
AUTOINSTALL=yes
