PACKAGE_NAME=xt_setset
pushd `dirname $BASH_SOURCE`
PACKAGE_VERSION=`./version.sh`
popd
BUILT_MODULE_NAME[0]=xt_setset
DEST_MODULE_LOCATION[0]=/kernel/extra
STRIP[0]=no
X4B_BUILD_BANSET=0
if ./check-banset-kernel.sh "$kernelver"; then
    BUILT_MODULE_NAME[1]=xt_banset
    DEST_MODULE_LOCATION[1]=/kernel/extra
    STRIP[1]=no
    X4B_BUILD_BANSET=1
fi
MAKE[0]="make xt_setset.ko X4B_BUILD_BANSET=$X4B_BUILD_BANSET KCFLAGS=-O3"
PRE_BUILD="./configure --from-dkms-conf=$kernel_source_dir"
AUTOINSTALL=yes
